=== bkan0n/noelle/data/character_build_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "character_name": {
        "type": "string"
      },
      "guide_video_url": {
        "type": "string",
        "format": "uri"
      },
      "guide_image_url": {
        "type": "string",
        "format": "uri"
      },
      "character_icon_url": {
        "type": "string",
        "format": "uri"
      },
      "element": {
        "type": "string",
        "enum": ["pyro", "cryo", "hydro", "dendro", "anemo", "geo", "electro"]
      }
    },
    "required": [
      "character_name",
      "guide_image_url",
      "character_icon_url",
      "element"
    ],
    "additionalProperties": false
  }
}

=== bkan0n/noelle/data/character_build_data.json
[
     {
    "character_name": "Mona",
    "guide_video_url": "https://www.youtube.com/watch?v=a-KWZUe1IOw",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1416898679130030234/Mona.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372697903553974322/UI_AvatarIcon_Mona.webp",
    "element": "hydro"
  },
  {
    "character_name": "Yumemizuki Mizuki",
    "guide_video_url": "https://youtu.be/V5PtfNYVwd4?si=LyQlCnxq7UAW9_YN",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1416898700025794722/Yumemizuki_Mizuki.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372699883319988264/UI_AvatarIcon_Mizuki.webp",
    "element": "anemo"
  },
  {
    "character_name": "Nahida",
    "guide_video_url": "https://youtu.be/wDHIyXgJT5o",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1416898731369824356/Nahida.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372698789575659610/UI_AvatarIcon_Nahida.png",
    "element": "dendro"
  },
  {
    "character_name": "Aino",
    "guide_video_url": "https://youtu.be/uQMv_rS1rVA",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1416898754090500116/Aino.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1400247346939428885/UI_AvatarIcon_Aino.png",
    "element": "hydro"
  },
  {
    "character_name": "Keqing",
    "guide_video_url": "https://www.youtube.com/watch?v=MSU4wMo2I0w",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1416898774269431858/Keqing.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372699922750640209/UI_AvatarIcon_Keqing.webp",
    "element": "electro"
  },
   {
    "character_name": "Qiqi",
    "guide_video_url": "",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1416898798789201981/Qiqi.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372697863359959090/UI_AvatarIcon_Qiqi.png",
    "element": "cryo"
  },
  {
    "character_name": "Jean",
    "guide_video_url": "https://youtu.be/QoaL6W53vWk?si=G_jay51bMft8YM0w",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1416898818196246528/Jean.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372697704823783534/UI_AvatarIcon_Qin.webp",
    "element": "anemo"
  },
  {
    "character_name": "Diluc",
    "guide_video_url": "",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1416898840111349980/Diluc.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372697747576193105/UI_AvatarIcon_Diluc.png",
    "element": "pyro"
  },
  {
    "character_name": "Lauma",
    "guide_video_url": "https://youtu.be/pgrjAoc8-PE?si=aNmbI6JqF3c3VBwZ",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1416898854619582544/Lauma.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1400247306791419994/UI_AvatarIcon_Lauma.png",
    "element": "dendro"
  },
  {
    "character_name": "Kaveh",
    "guide_video_url": "https://youtu.be/V4YQp2sDiic",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1416898879940464833/Kaveh.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372701054197567529/UI_AvatarIcon_Kaveh.webp",
    "element": "dendro"
  },
  {
    "character_name": "Barbara",
    "guide_video_url": "https://youtu.be/JK6BsDcUYkA",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1416898926891630613/Barbara.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372700100765417582/UI_AvatarIcon_Barbara.webp",
    "element": "hydro"
  },
  {
    "character_name": "Kuki Shinobu",
    "guide_video_url": "https://youtu.be/_g44041Nx_4",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1416898942846894101/Kuki.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372700773250629782/UI_AvatarIcon_Shinobu.png",
    "element": "electro"
  },
  {
    "character_name": "Chasca",
    "guide_video_url": "https://youtu.be/NzfGfns7lSI",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1407413153444134984/Chasca.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372699683193098402/UI_AvatarIcon_Chasca.webp",
    "element": "anemo"
  },
  {
    "character_name": "Mualani",
    "guide_video_url": "https://youtu.be/Nha-fMcVPr8",
    "guide_image_url": "https://media.discordapp.net/attachments/1372677952030117948/1407413235795099718/Mualani.png",
    "character_icon_url": "https://media.discordapp.net/attachments/1372677919624790076/1372699607917789244/UI_AvatarIcon_Mualani.webp",
    "element": "hydro"
  },
  {
    "character_name": "Ifa",
    "guide_video_url": "https://youtu.be/8ipwYcCbCAo",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1407413178127749231/Ifa.png",
    "character_icon_url": "https://media.discordapp.net/attachments/1372677919624790076/1372701346628763658/UI_AvatarIcon_Ifa.webp",
    "element": "anemo"
  },
  {
    "character_name": "Ororon",
    "guide_video_url": "https://youtu.be/ck5y9lpRJBA",
    "guide_image_url": "https://media.discordapp.net/attachments/1372677952030117948/1407413208662147113/Ororon.png",
    "character_icon_url": "https://media.discordapp.net/attachments/1372677919624790076/1372701285362434078/UI_AvatarIcon_Olorun.png",
    "element": "electro"
  },
  {
    "character_name": "Bennett",
    "guide_video_url": "https://youtu.be/XIGDqABn7oc",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1407413136906129448/Bennett.png",
    "character_icon_url": "https://media.discordapp.net/attachments/1372677919624790076/1372700391610781896/UI_AvatarIcon_Bennett.webp",
    "element": "pyro"
  },
  {
    "character_name": "Sethos",
    "guide_video_url": "https://www.youtube.com/watch?v=b0W67jAEwwc",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1403132143135359056/Sethos.png",
    "character_icon_url": "https://media.discordapp.net/attachments/1372677919624790076/1372701237790642266/UI_AvatarIcon_Sethos.webp",
    "element": "electro"
  },
  {
    "character_name": "Fischl",
    "guide_video_url": "https://youtu.be/BgVjMn-ymYE?si=PeVMYeqwMv3wBCHk",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1403132172809797632/Fischl.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372700365341986949/UI_AvatarIcon_Fischl.png",
    "element": "electro"
  },
  {
    "character_name": "Xingqiu",
    "guide_video_url": "https://www.youtube.com/watch?v=P4eaH4bhco0",
    "guide_image_url": "https://media.discordapp.net/attachments/1372677952030117948/1403137876195282994/Xingqiu.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372700287130796223/UI_AvatarIcon_Xingqiu.png",
    "element": "hydro"
  },
  {
    "character_name": "Ineffa",
    "guide_video_url": "https://youtu.be/5VQip1ayjis",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1400817930391781417/Ineffa.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1384878265524817950/UI_AvatarIcon_Ineffa.png",
    "element": "electro"
  },
  {
    "character_name": "Citlali",
    "guide_video_url": "https://youtu.be/CJnjjN2uPao",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1400817903292645386/Citlali.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372699849514025020/UI_AvatarIcon_Citlali.webp",
    "element": "cryo"
  },
  {
    "character_name": "Dehya",
    "guide_video_url": "https://www.youtube.com/watch?v=KaXSnW6yrK0",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1397701535529435266/Dehya.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372698930055348414/UI_AvatarIcon_Dehya.webp",
    "element": "pyro"
  },
  {
    "character_name": "Tighnari",
    "guide_video_url": "https://www.youtube.com/watch?v=cImazvnkKE8",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1397701554508922920/Tighnari.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372698670784450570/UI_AvatarIcon_Tighnari.webp",
    "element": "dendro"
  },
  {
    "character_name": "Iansan",
    "guide_video_url": "https://youtu.be/DKmEYez0QOk",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1393775176000340049/Iansan.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372701330711380130/UI_AvatarIcon_Iansan.webp",
    "element": "electro"
  },
  {
    "character_name": "Xiangling",
    "guide_video_url": "https://youtu.be/DDgzGnfUHt0",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1393635268061560994/Xiangling.png",
    "character_icon_url": "https://cdn.discordapp.com/attachments/1372677919624790076/1372700228146298900/UI_AvatarIcon_Xiangling.webp",
    "element": "pyro"
  },
  {
    "character_name": "Yaoyao",
    "guide_video_url": "https://youtu.be/lXC5l4ypRco",
    "guide_image_url": "https://cdn.discordapp.com/attachments/1372677952030117948/1393635284398248008/Yaoyao.png",
